// <auto-generated />
namespace Assignmnet9.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fix32 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix32));
        
        string IMigrationMetadata.Id
        {
            get { return "201604111949441_fix32"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
